### PR TITLE
Ansible chef resources

### PR DESCRIPTION
**Pull request by mercenarysre**
Added resources for Ansible and Chef respectively.
@rishabkumar7 kindly review, thanks.

### CODE REVIEW

**Comment by rishabkumar7** [comment]
Thanks @TomiwaAribisala-git for the contribution, it looks good, but the audio quality on the resource for Chef (playlist) is terrible, I was thinking we should replace that with this video - https://youtu.be/04oITjdLtho

**Comment by mercenarysre** [comment]
@rishabkumar7 thanks for the review, I have updated the Chef resource with your suggested tutorial.

**Comment by rishabkumar7** [comment]
LGTM 👍🏽

**Review by rishabkumar7 — COMMENTED** [review]
lgtm

**Pull request merged**
